# Generated by Django 3.2.4 on 2021-09-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_activ',
            new_name='is_active',
        ),
    ]
