# Generated by Django 3.2.4 on 2021-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mane', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='discription',
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
