# Generated by Django 3.2.4 on 2021-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mane', '0004_auto_20210718_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='liked',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
