# Generated by Django 3.2.4 on 2021-07-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mane', '0005_photo_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(max_length=150, verbose_name='Тип новости')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок новости')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('news', models.TextField(blank=True, null=True, verbose_name='Описание новости')),
                ('date_creat', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_public', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='News_Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Введение')),
            ],
        ),
    ]
