# Generated by Django 3.2.4 on 2021-07-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mane', '0006_news_news_bloc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='News_Bloc',
        ),
    ]
